name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: paewhal20/movie
          stage: main
          yaml: |
            name: movieticket
            app: java@17
            options:
              ports: 8080
              env:
                - name: JWT_SECRET
                  value: ${{ secrets.JWT_SECRET }}
                - name: MAIL_ID
                  value: paewhal20
                - name: MAIL_PW
                  value: ${{ secrets.MAIL_ID }}
                - name: DB_PWD
                  value: ${{ secrets.DB_PWD }}
                - name: DB_USER_NAME
                  value: ${{ secrets.DB_USER_NAME }}
                - name: S3_ACCESS_KEY
                  value: ${{ secrets.S3_ACCESS_KEY }}
                - name: S3_BUCKET_NAME
                  value: ${{ secrets.S3_BUCKET_NAME }}
                - name: S3_SECRET_KEY
                  value: ${{ secrets.S3_SECRET_KEY }}
                - name: DB_HOST
                  value: ${{ secrets.DB_HOST }}
                - name: REDIS_HOST
                  value: ${{ secrets.REDIS_HOST }}
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
